urls:
  sample1:
    samplestringyahonexters

string:
  regex:
    base62:
      abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789

encode:
  base62:
    62

spring:
  h2:
    console:
      enabled: true


# https://m.post.naver.com/viewer/postView.nhn?volumeNo=17415587&memberNo=1957461&vType=VERTICAL

